ackermann_steering_controller:
  type: "ackermann_steering_controller/AckermannSteeringController"
  left_steering_joint: "front_left_steering_joint" 
  right_steering_joint: "front_right_steering_joint"  # for symmetry, usually same as left
  left_wheel_joint: "rear_left_wheel_joint"
  right_wheel_joint: "rear_right_wheel_joint"
  publish_rate: 50
  ackermann_cmd_timeout: 0.5
  linear:
    max_velocity: 3.0    # Max linear velocity in m/s
  angular:
    max_steering_angle: 0.785  # Max steering angle in radians (~45 degrees)